// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5wlVrOWBvKjtlXBdbRi2cJmgDKkQUE7I',
    appId: '1:1097338854367:web:4c8cc04312c1122042c26a',
    messagingSenderId: '1097338854367',
    projectId: 'nabung-yuk-58baf',
    authDomain: 'nabung-yuk-58baf.firebaseapp.com',
    storageBucket: 'nabung-yuk-58baf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYyTHv4R2x4r49bhPBkdgnhkBDIzMUDs8',
    appId: '1:1097338854367:android:008b8f68c4c3ce6d42c26a',
    messagingSenderId: '1097338854367',
    projectId: 'nabung-yuk-58baf',
    storageBucket: 'nabung-yuk-58baf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVN_UdM93XvRihecAqqa4l-cbLYVGP67Q',
    appId: '1:1097338854367:ios:b4983d27ac5e969642c26a',
    messagingSenderId: '1097338854367',
    projectId: 'nabung-yuk-58baf',
    storageBucket: 'nabung-yuk-58baf.appspot.com',
    iosClientId: '1097338854367-bp326kqf6qg4s21cv2uua03fh05o79cr.apps.googleusercontent.com',
    iosBundleId: 'com.example.nabungYuk',
  );
}
